apiVersion: v1
kind: Service
metadata:
  name: morefair
  namespace: morefair
  labels:
    app: morefair
spec:
  ports:
    - port: 8080
      targetPort: morefair
      name: morefair
  selector:
    app: morefair
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: morefair
spec:
  type: ExternalName
  externalName: postgres.postgres.svc.cluster.local
  ports:
  - port: 5432